---
apiVersion: v1
offerings:
  - name: deploy-arch-ibm-observability-agents
    kind: solution
    catalog_id: _
    offering_id: _
    variations:
      - name: standard
        mark_ready: true
        install_type: extension
        pre_validation: "tests/scripts/pre-validation-deploy-slz-roks-and-obs-instances.sh"
        post_validation: "tests/scripts/post-validation-destroy-slz-roks-and-obs-instances.sh"
