---
apiVersion: v1
offerings:
  - name: deploy-arch-ibm-observability-agents
    kind: solution
    catalog_id: 7df1e4ca-d54c-4fd0-82ce-3d13247308cd
    offering_id: d4ed02f5-0aa5-4e03-a9cb-7913ab2da27f
    variations:
      - name: fully-configurable
        mark_ready: true
        install_type: fullstack
        pre_validation: "tests/scripts/pre-validation-deploy-slz-roks-and-obs-instances.sh"
        post_validation: "tests/scripts/post-validation-destroy-slz-roks-and-obs-instances.sh"
