apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: "{{ .Values.metadata.name }}"
  labels:
    app.kubernetes.io/name: "{{ .Values.metadata.name }}"
    app.kubernetes.io/instance: "{{ .Values.metadata.name }}"
    app.kubernetes.io/version: {{ .Values.image.version }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get","list", "create", "watch"]
