apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.metadata.name }}
    version: {{ required "Missing version" .Values.image.version }}
