kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.metadata.name }}
  labels:
    app: {{ .Values.metadata.name }}
    version: {{ required "Missing version" .Values.image.version }}
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
      - nodes/proxy
    verbs:
      - get
      - list
      - watch
