{{- if hasKey .Values "secret"}}
{{- if .Values.secret.iamAPIKey }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ .Values.metadata.name }}
    version: {{ required "Missing version" .Values.image.version }}
  name: {{ .Values.metadata.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  IAM_API_KEY: {{ .Values.secret.iamAPIKey | quote }}
{{- end }}
{{- end }}