apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: "{{ .Values.metadata.name }}-ds-priority"
  namespace: {{ .Release.Namespace }}
value: 1000000
preemptionPolicy: PreemptLowerPriority
globalDefault: false
description: "Logdna Agent"
