apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Values.metadata.name }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: "{{ .Values.metadata.name }}"
    app.kubernetes.io/instance: "{{ .Values.metadata.name }}"
    # Extracts the first part before '@' from .Values.image.version, ensuring it's treated as a string.
    app.kubernetes.io/version: {{ .Values.image.version | default "" | toString | splitList "@" | first }}
  annotations:
    {{- range .Values.checkov_skips }}
    {{- . | toYaml | nindent 4 -}}
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ .Values.metadata.name }}"
subjects:
  - kind: ServiceAccount
    name: "{{ .Values.metadata.name }}"
    namespace: {{ .Release.Namespace }}
