apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.metadata.name }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: "{{ .Values.metadata.name }}"
    app.kubernetes.io/instance: "{{ .Values.metadata.name }}"
    app.kubernetes.io/version: {{ .Values.image.version }}
