apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloud-monitoring-agent
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: cloud-monitoring-agent
    app.kubernetes.io/instance: cloud-monitoring-agent
    app.kubernetes.io/version: {{ .Values.image.version }}
  annotations:
    {{- range .Values.checkov_skips }}
    {{- . | toYaml | nindent 4 -}}
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloud-monitoring-agent
subjects:
  - kind: ServiceAccount
    name: cloud-monitoring-agent
    namespace: {{ .Release.Namespace }}
