kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: ibm-privileged-scc-cloud-monitoring
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: cloud-monitoring-agent
    app.kubernetes.io/instance: cloud-monitoring-agent
    app.kubernetes.io/version: {{ .Values.image.version }}
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities:
- '*'
allowedUnsafeSysctls:
- '*'
defaultAddCapabilities: []
defaultAllowPrivilegeEscalation: true
fsGroup:
  type: RunAsAny
groups: []
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities: []
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
- '*'
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:{{ .Release.Namespace }}:cloud-monitoring-agent
volumes:
- '*'
