apiVersion: v1
data:
  access-key: "{{ required "Sysdig Secret Key must be provided" .Values.secret.key | b64enc }}"
kind: Secret
metadata:
  name: "{{ .Values.secret.name }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: "{{ .Values.metadata.name }}"
    app.kubernetes.io/instance: "{{ .Values.metadata.name }}"
    app.kubernetes.io/version: {{ .Values.image.version }}
type: Opaque
