apiVersion: v1
data:
  access-key: "{{ required "Sysdig Secret Key must be provided" .Values.secret.key | b64enc }}"
kind: Secret
metadata:
  name: sysdig-agent
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: sysdig-agent
    app.kubernetes.io/instance: sysdig-agent
    app.kubernetes.io/version: {{ .Values.image.version }}
type: Opaque
