apiVersion: v1
kind: ServiceAccount
metadata:
  name: sysdig-agent
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: sysdig-agent
    app.kubernetes.io/instance: sysdig-agent
    app.kubernetes.io/version: {{ .Values.image.version }}
  annotations:
    {{- range .Values.checkov_skips }}
    {{- . | toYaml | nindent 4 -}}
    {{- end }}
