metadata:
  name: "logs-router-agent"
image:
  version: "1.2.3" # required
env:
  # ingestionHost is a required field. For example:
  # ingestionHost: "ingester.private.us-east.logs-router.cloud.ibm.com"
  ingestionHost: "" # required unless 'sendDirectlyToICL.enabled' is set to true.

  # If you are using CSE proxy, then use port number "3443" or if you are using private VPE Gateway, then use port number "443".
  ingestionPort: "" # required unless 'sendDirectlyToICL.enabled' is set to true.

  # iamMode: "TrustedProfile" or "IAMAPIKey"
  iamMode: "TrustedProfile"
  # iamEnvironment: "Production" or "Staging"
  iamEnvironment: "Production"

  # trustedProfileID - trusted profile id - required for iam trusted profile mode
  trustedProfileID: "" # required if iamMode is TrustedProfile

# These optional subsystemName and subSystemApplicationName will be used in filter-add-ICL-meta-data.conf if they are not empty
filterAddICLmetadata:
  subsystemName: ""
  applicationName: ""

# Normally you don't need to change the default resource values
resources:
  limits:
    cpu: 500m
    ephemeral_storage: 10Gi
    memory: 3Gi
  requests:
    cpu: 100m
    ephemeral_storage: 2Gi
    memory: 1Gi

# comma separated list, for example “/var/log/abc/*.log,/var/log/xyz/*.log”
additionalLogSourcePaths: ""
excludeLogSourcePaths: ""

cluster:
  name: "" # required

scc:
  # true here enables creation of Security Context Constraints in Openshift
  create: true

# Optional: Set 'enabled' to true to send logs directly to {{site.data.keyword.logs_full_notm}}, bypassing the ICLR data plane.
# Note: This option is intended for scenarios where multiple {{site.data.keyword.logs_full_notm}} instances exist within the same account,
# enabling advanced logging configurations. For instance, you can direct logs from different environments (e.g., development, production)
# to separate target instances within the same account.
sendDirectlyToICL:
  enabled: false
  targetHost: "" # Specify the host for ICL ingestion (found in the Endpoints section of the ICL instance Overview). Ensure you use the ingress endpoint.
  targetPort: "" # Specify the port for ICL ingestion (use the ICL ingress endpoint port).
